manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: refil
      url-base: https://github.com/ReFil
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: refil
      revision: kssbtest
      import: app/west.yml
    - name: gpio-rgb-zephyr-module
      remote: refil
      revision: main
  self:
    path: config